name: Docker

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/build.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  Docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: define telegram API token
        run: echo ${{ secrets.TG_PROD_TOKEN }} > app/config

      - name: decode and define opt.json
        run: |
          echo '${{ secrets.OPT_JSON }}' base64 -d > app/opt.json
          if [ -f "app/opt.json" ]; then
            echo "File opt.json exists"
          else
            echo "File opt.json does not exist"
            exit 1
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

# Download artifact, rds,
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ventureronin/tg_weatherbot:latest
#
#      -
#        name: Image digest
#        run: echo ${{steps.docker_build.outputs.digest }}