name: CI/CD

on:
  push:
    paths:
      - '.github/workflows/deploy.yml'
    branches:
      - main
  workflow_run:
    workflows: Build
    types:
      - completed
  workflow_dispatch:

jobs:
  aws-init-bot:
    name: 'AWS auth, and setup&run script'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS
        run: apt-get install awscli

      - name: Awscli set up
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-north-1a

      - name: AWS scp
        run: scp -i ${{ secrets.AWS_SSH_KEY }} scripts/docker-login-pull.sh ubuntu@ec2-13-48-24-243.eu-north-1.compute.amazonaws.com:docker-login-pull.sh

      - name: AWS chmod&exec script (ssh)
        run: ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@ec2-13-48-24-243.eu-north-1.compute.amazonaws.com "sudo chmod +x docker-login-pull.sh && ./docker-login-pull.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}"
