name: CI/CD

on:
  workflow_run:
    workflows: build
    types:
      - completed
  workflow_dispatch:

jobs:
  gcp-init-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#          create_credentials_file: false

      - name: SSH into Gcloud
        id: 'compute-ssh'
        uses: google-github-actions/ssh-compute@v0
        with:
          instance_name: 'instance-template-1'
          zone: 'europe-north1-b'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'
#          |
#            pwd
#            ls -la
#            ls -la scripts
#            scripts/docker-login-pull.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}