name: CI/CD

on:
  push:
    paths:
      - '.github/workflows/deploy.yml'
    branches:
      - main
  workflow_run:
    workflows: build
    types:
      - completed
  workflow_dispatch:

jobs:
  gcp-init-bot:
    name: 'GCP auth, and setup&run script'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#          create_credentials_file: false

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Test gcloud sdk
        run: gcloud config list

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download container
        run: docker pull ventureronin/tg_weatherbot:latest

      - name: Pack container into tar
        run: docker save -o bot_image.tar ventureronin/tg_weatherbot:latest

      - name: Gcloud scp
        run: |
          gcloud compute scp bot_image.tar instance-template-1:bot_image.tar --zone=europe-north1-b
          gcloud compute ssh instance-template-1 --zone=europe-north1-b --command="docker load -i bot_image.tar"
        #runner@${{ env.GCP_IP }} --ssh-key-file=${{ secrets.SSH_PRIVATE_KEY }}
        
#      - name: SSH into Gcloud
#        id: 'compute-ssh'
#        uses: google-github-actions/ssh-compute@v0
#        with:
#          instance_name: 'instance-template-1'
#          zone: 'europe-north1-b'
#          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
#          command: |
#            sudo chmod +x ${{ github.workspace }}/scripts/docker-login-pull.sh
#            ./${{ github.workspace }}/scripts/docker-login-pull.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}