name: Weather_Bot_inGCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_NAME: ${{ secrets.DOCKER_REPONAME }}
  DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
  SA_NAME: ${{ secrets.SA_ACCOUNT }}
  REGION: us-central1
  REPO: ventureronin/WeatherBot

jobs:          
  terraform-ci1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Decode credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials.json
          if [ -f "credentials.json" ]; then
            echo "File credentials.json exists"
            chmod 777 credentials.json
          else
            echo "File credentials.json does not exist"
            exit 1
          fi

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_PROJECT_ID }}"
          gcloud config set account ${SA_NAME}
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: terraform init
        run: |
          terraform init
          ls

      - name: terraform plan
        id: plan
        run: terraform plan -lock=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform apply
        if: "!contains(github.event.head_commit.message, 'destroy')"
        run: terraform apply -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
        
  terraform-CI:
    needs: terraform-ci1
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_LOGIN/$DOCKER_NAME:${GITHUB_REF:11} -f Dockerfile .
        
      - name: Push Docker image
        run: docker push $DOCKER_LOGIN/$DOCKER_NAME:${GITHUB_REF:11}
        
      - name: Decode credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials.json
          if [ -f "credentials.json" ]; then
            echo "File credentials.json exists"
            cat credentials.json
            chmod 777 credentials.json
          else
            echo "File credentials.json does not exist"
            exit 1
          fi

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_PROJECT_ID }}"
          gcloud config set account ${SA_NAME}
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Check GCP permissions 2
        run: gcloud auth list
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform plan
        id: plan
        run: terraform plan -lock=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform apply
        if: "!contains(github.event.head_commit.message, 'destroy')"
        run: terraform apply -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform destroy
        if: contains(github.event.head_commit.message, 'destroy')
        run: terraform destroy -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
