name: Weather_Bot_inGCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SA_NAME: ${{ secrets.sa_account }}
  REGION: us-central1
  REPO: ventureronin/WeatherBot

jobs:
  terraform-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t tgweatherbotpy .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push tgweatherbotpy

      - name: Decode credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | base 64 -d > credentials.json

      - name: Authenticate with Google Cloud
        run: |
          gcloud config set account ${SA_NAME}
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: terraform init
        run: terraform init

      - name: terraform plan
        id: plan
        run: terraform plan -lock=false -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform apply
        if: "!contains(github.event.head_commit.message, 'destroy')"
        run: terraform apply -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"

      - name: terraform destroy
        if: contains(github.event.head_commit.message, 'destroy)
        run: terraform destroy -lock=false -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
