name: terraform

on:
  push:
    paths:
      - '.github/workflow/terraform.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download container
        run: docker pull ventureronin/tg_weatherbot:latest

      - name: Decode credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > credentials.json
          if [ -f "credentials.json" ]; then
            echo "File credentials.json exists"
            chmod 777 credentials.json
          else
            echo "File credentials.json does not exist"
            exit 1
          fi

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_PROJECT_ID }}"
          gcloud config set account ${{ secrets.SA_ACCOUNT }}
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Check GCP permissions
        run: gcloud auth list
